import { RouteLocationNormalized } from 'vue-router';

export default [
  {
    path: '/cards',
    name: 'Cards',
    component: () => import('@/arkham/views/Cards.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Cards" },
    props: true,
  },
  {
    path: '/deck/:deckId',
    name: 'Deck',
    component: () => import('@/arkham/views/Deck.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Deck" },
    props: true,
  },
  {
    path: '/decks',
    name: 'Decks',
    component: () => import('@/arkham/views/Decks.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Decks" },
    props: true,
  },
  {
    path: '/campaigns/new',
    name: 'NewCampaign',
    component: () => import('@/arkham/views/NewCampaign.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: New Game" },
    props: true,
  },
  {
    path: '/events/:id',
    name: 'OrganizerDashboard',
    component: () => import('@/arkham/views/OrganizerDashboard.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Organizer Dashboard" },
    props: true,
  },
  {
    path: '/games/:gameId',
    name: 'Game',
    component: () => import('@/arkham/views/Game.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror" },
    props: true,
  },
  {
    path: '/admin/games/:gameId',
    name: 'AdminGame',
    component: () => import('@/arkham/views/Game.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror" },
    props: (route: RouteLocationNormalized) => ({ ...route.params, spectate: true }),
  },
  {
    path: '/games/:gameId/spectate',
    name: 'Spectate',
    component: () => import('@/arkham/views/Game.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Spectate" },
    props: (route: RouteLocationNormalized) => ({ ...route.params, spectate: true }),
  },
  {
    path: '/games/:gameId/log',
    name: 'CampaignLog',
    component: () => import('@/arkham/views/CampaignLog.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Campaign Log" },
    props: true,
  },
  {
    path: '/games/:gameId/join',
    name: 'JoinGame',
    component: () => import('@/arkham/views/JoinGame.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Join Game" },
    props: true,
  },
  {
    path: '/games/:gameId/claim-seat',
    name: 'ClaimSeat',
    component: () => import('@/arkham/views/ClaimSeat.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Claim Seat" },
    props: true,
  },
  {
    path: '/games/:gameId/replay',
    name: 'ReplayGame',
    component: () => import('@/arkham/views/ReplayGame.vue'),
    meta: { requiresAuth: true, title: "Arkham Horror: Replay" },
    props: true,
  },
];
