---
require-stack-version: ">= 2.9.3"
concurrent-tests: false
system-ghc: true
install-ghc: false
resolver: nightly-2023-05-17
compiler: ghc-9.4.5

ghc-options:
  "$locals":
    -fwrite-ide-info
    -fhide-source-paths
    -fignore-optim-changes
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-kind-signatures
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-safe-haskell-mode

packages:
  - cards-discover
  - arkham-core
  - arkham-api
  - validate

allow-newer: true

extra-deps:
- happy-1.20.1.1
- github: jmazon/clientsession
  commit: 1221230770feff60f77ff676d52fc464cb77b2d9
