---
require-stack-version: ">= 2.3.1"
concurrent-tests: false

system-ghc: true
install-ghc: false
resolver: nightly-2022-11-01
compiler: ghc-9.4.3

ghc-options:
  "$locals":
    -fhide-source-paths
    -Weverything
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-kind-signatures
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -fignore-optim-changes
    -Wno-missing-safe-haskell-mode
    -Wno-prepositive-qualified-module
    -fwrite-ide-info
    -hiedir=.hie

packages:
  - cards-discover
  - arkham-core
  - arkham-api
  - validate

extra-deps:
- Cabal-syntax-3.8.1.0
- primitive-0.7.4.0
- memory-0.18.0
