---
require-stack-version: ">= 3.7.1"
concurrent-tests: true
system-ghc: true
install-ghc: false
resolver: nightly-2025-07-31
compiler: ghc-9.12.2
notify-if-nix-on-path: false

ghc-options:
  "$locals":
    -O0
    -fwrite-ide-info
    -hiedir=.hie
    -fhide-source-paths
    -fignore-optim-changes
    -Weverything
    -Wno-unused-packages
    -Wno-missing-exported-signatures
    -Wno-missed-specialisations
    -Wno-all-missed-specialisations
    -Wno-unsafe
    -Wno-safe
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-missing-kind-signatures
    -Wno-missing-import-lists
    -Wno-missing-export-lists
    -Wno-incomplete-uni-patterns
    -Wno-partial-fields
    -Wno-implicit-prelude
    -Wno-deriving-typeable
    -Wno-missing-safe-haskell-mode
    -Wno-missing-role-annotations
    -Wno-term-variable-capture
    -Wno-missing-poly-kind-signatures

packages:
  - cards-discover
  - arkham-api
  - validate

allow-newer: true

extra-deps:
- github: halogenandtoast/monad-validate
  commit: e5f36d4a82875c09c6000fed8f8ced50e21b75ce
- github: brendanhay/amazonka
  commit: 4873cc451113147d071721c97704ac648d71e9ee
  subdirs:
    - lib/amazonka
    - lib/amazonka-core
    - lib/services/amazonka-sso
    - lib/services/amazonka-sts
    - lib/services/amazonka-s3
- jwt-0.11.0@sha256:0602735ee4093c6c5bc918461855bcd55499099363bad34eb7a227aeef3cde29,4265
- cryptostore-0.3.1.0@sha256:ce4762361b509d1719b5d500604a5a1f2d75c2c53f4fe75f7c4ef2faec4f8352,4219
- x509-1.7.7@sha256:90eef2d745a654146fc1c325e035eaddac531e4d2145d4bc1dcf4b8fad439d34,2276
- x509-store-1.6.9@sha256:1f1abeab5bacf1407b920d0f34f4c35a5ad450ff0d8121cd3dc76460f81e711d,1716
- x509-validation-1.6.12@sha256:4f4af20ec77f02c042ecd4726c195bb0e0b694b336de81e7bd4515b2917bd9bc,2169
- cryptonite-0.30@sha256:12c85dea7be63e5ad90bcb487eb3846bf3c413347f94336fa1dede7b28f9936a,18301
- persistent-postgresql-2.13.6.2@sha256:f455dcac3145d9f26f95ce2605074785641478bc226071f458995b2b8051a8a8,3809
- yesod-test-1.6.19@sha256:faac869ab6fa86113cde99d28928e196373a04879c03204071956954ed7ba2a3,3003
- postgresql-simple-0.7.0.0@sha256:6ada584a2e6c8f8d6cb695ceddfb0600bfe3f320ccb6cec99ca1a2f0a38d6ded,4772
