// Chinese (zh) UI-control translation patch for ArkhamHorror frontend.
// Keys are flat dot-paths; values preserve i18next placeholders:
//   {name} {count} {total} {n} {slot} @:{slot} @:{fromSlot} {'{'}curse{'}'} {'{'}frost{'}'}
// and plural separators "|" and HTML tags <strong>/<br>/<p>/<ul>/<li>.
export default {
  "checkCampaignLog": `查看你的战役日志。`,
  "elusive.flee": `难以捕捉：为该敌人选择一个相连地点以逃离。`,
  "hunter.move": `猎手：为该敌人选择一个移动目标地点。`,
  "patrol.move": `巡逻：为该敌人选择一个移动目标地点。`,
  "discard": `弃置 {name}`,
  "waitingForPlayer": `等待 {name}…`,
  "Reaction": `反应`,
  "token.Kindling": `火种`,
  "choice.damage": `伤害`,
  "slot.head": `头部`,
  "fromEncounterDeck": `来自遭遇牌库`,
  "fromEncounterDiscard": `来自遭遇弃牌堆`,
  "lobby.takeASeat": `就座`,
  "waitingOn.label": `等待该调查员`,
  "cardsView.cardPool": `卡池`,
  "cardsView.playerCards": `玩家`,
  "cardsView.campaignCards": `战役`,
  "cardsView.bothCards": `全部`,
  "sideStory.requiresInvestigator": `需要 {name}`,
  "sideStory.xpAsymmetric": `（{signatureXp} 经验给 {name}，每名其他调查员 {otherXp} 经验）`,
  "campaignLog.specialRules": `特殊规则`,
  "campaignLog.campaignRules": `战役规则`,
  "campaignLog.backToTop": `返回顶部`,
  "campaignLog.noRules": `当前场景或战役没有特殊规则。`,
  "campaignLog.tabs.log": `战役日志`,
  "campaignLog.tabs.investigators": `调查员`,
  "campaignLog.tabs.rules": `规则`,
  "deckRestrictions.scarletKeys.redGlovedMan.description": `红手套男无法被纳入。`,
  "deckRestrictions.scarletKeys.redGlovedMan.error": `猩红密钥战役无法纳入红手套男。`,
  "settingsForm.epicMultiplayer": `史诗多人模式（开发）`,
  "settingsForm.epicMultiplayerWarning": `史诗多人模式正在积极开发中——目前尚不可用。仅用于测试时开启。`,
  "settingsForm.aiInvestigators": `AI 调查员（开发）`,
  "settingsForm.aiInvestigatorsWarning": `实验性功能且尚未可用——正在积极开发中。开启可能导致游戏异常或行为不可预期。`,
  "debug.asset.flip": `翻转`,
  "debug.story.title": `调试剧情`,
  "debug.story.inspectBag": `查看混沌袋`,
  "debug.story.empty": `混沌袋内没有可显示的内容。`,
  "event.events": `史诗多人活动`,
  "event.epicMultiplayer": `史诗多人`,
  "event.organizerDashboard": `组织者面板`,
  "event.scenario": `场景`,
  "event.countermeasures": `反制措施`,
  "event.totalInvestigators": `调查员总数`,
  "event.investigators": `调查员`,
  "event.seats": `{count} / {total} 个座位`,
  "event.openSeats": `空座位`,
  "event.joinable": `可加入`,
  "event.full": `已满`,
  "event.open": `开放`,
  "event.copyInviteLink": `复制邀请链接`,
  "event.inviteLinkCopied": `链接已复制！`,
  "event.joinThisGroup": `加入该小组`,
  "event.notStarted": `未开始`,
  "event.inProgress": `进行中`,
  "event.decrement": `减少反制措施`,
  "event.increment": `增加反制措施`,
  "event.loading": `正在加载活动…`,
  "event.disconnected": `正在重新连接…`,
  "event.deleteEvent": `删除活动`,
  "event.confirmDelete": `删除该活动及其所有小组游戏？此操作无法撤销。`,
  "event.playMySeat": `游玩我的座位`,
  "event.returnToOrganizerView": `返回组织者视图`,
  "event.playing": `游戏中`,
  "event.spectate": `观战`,
  "event.spectating": `观战中`,
  "event.communicateHint": `调查员可在各小组间自由交流。`,
  "event.timeRemaining": `剩余时间`,
  "event.sharedClues": `共享线索`,
  "event.awaitingOrganizer": `已准备推进行动——等待组织者`,
  "event.openDashboardToAllocate": `打开组织者面板以分配线索`,
  "event.allocateAdvance": `推进剧本阶段 {stage}`,
  "event.allocateAdvanceHint": `选择每个小组为推进剧本所消耗的线索数。总数必须等于 {threshold}。`,
  "event.allocateAvailable": `{count} 个可用`,
  "event.allocateTotal": `已分配：{total} / {threshold}`,
  "event.confirmAdvance": `推进剧本`,
  "event.waitingForGroups": `等待所有小组准备就绪…`,
  "event.players": `玩家`,
  "event.choosing": `选择中…`,
  "event.noPlayersYet": `暂无玩家`,
  "event.group": `小组 {ordinal}`,
  "event.role.organizer": `组织者`,
  "event.role.player": `玩家`,
  "gameBar.viewHistory": `查看历史`,
  "gameBar.playerSettings": `玩家设置`,
  "gameBar.viewSettingSkipTriggersTitle": `跳过触发`,
  "gameBar.viewSettingShowOtherPlayersHands": `始终查看其他玩家手牌中的卡牌。`,
  "gameBar.viewSettingShowOtherPlayersHandsTitle": `显示其他玩家手牌`,
  "gameBar.debugExportScenario": `调试导出（场景）`,
  "gameBar.debugExportFull": `调试导出（完整）`,
  "gameBar.restartScenario": `重新开始场景`,
  "gameBar.fileBugPart3": `上传的调试文件仅包含最近 30 步，因此请确保你的问题在此范围内，或提供额外信息以便复现问题。`,
  "gameBar.rotateLayout": `旋转地点布局`,
  "historyPanel.title": `历史`,
  "historyPanel.round": `回合`,
  "historyPanel.phase": `阶段`,
  "historyPanel.turn": `行动轮`,
  "historyPanel.empty": `此范围内暂无记录。`,
  "historyPanel.section.counts": `统计`,
  "historyPanel.section.playedCards": `打出的卡牌`,
  "historyPanel.section.treacheriesDrawn": `抽到的诡计`,
  "historyPanel.section.enemiesDrawn": `抽到的敌人`,
  "historyPanel.section.enemiesDefeated": `击败的敌人`,
  "historyPanel.section.enemiesAttackedBy": `被其攻击的敌人`,
  "historyPanel.section.dealtDamageTo": `对其造成损害的`,
  "historyPanel.section.locationsInvestigated": `调查过的地点`,
  "historyPanel.section.cluesDiscovered": `发现的线索`,
  "historyPanel.section.skillTests": `技能检定`,
  "historyPanel.field.actionsCompleted": `完成的行动`,
  "historyPanel.field.actionsSpent": `消耗的行动`,
  "historyPanel.field.moved": `移动`,
  "historyPanel.field.cardsDrawn": `抽到的卡牌`,
  "historyPanel.field.resourcesGained": `获得的资源`,
  "historyPanel.field.attacksOfOpportunity": `机会攻击`,
  "historyPanel.field.successfulAttacks": `成功的攻击`,
  "historyPanel.field.successfulEvasions": `成功的闪避`,
  "historyPanel.field.successfulInvestigations": `成功的调查`,
  "historyPanel.field.successfulExplore": `成功的探索`,
  "historyPanel.skillResult.unrun": `未执行`,
  "historyPanel.skillResult.succeededBy": `成功，超出 {n}`,
  "historyPanel.skillResult.failedBy": `失败，相差 {n}`,
  "historyPanel.enemy.health": `生命：{n}`,
  "historyPanel.enemy.defeated": `已击败`,
  "historyPanel.clues.count": `线索：{n}`,
  "investigator.freeAbilitiesUnavailable": `<strong>无法使用免费能力</strong><br>在即时行动期间无法使用迅捷与免费能力。`,
  "upgrade.newInvestigator": `载入新调查员`,
  "upgrade.killed": `你的调查员已死亡或陷入疯狂。请选择一名新调查员。`,
  "upgrade.unspendableXp": `不可使用的经验`,
  "create.requiresInvestigator": `需要 {name}`,
  "create.bothScenarios": `两个场景（战役）`,
  "create.scenarios": `场景`,
  "create.playMode": `游戏模式`,
  "create.singleGroupMode": `单人小组模式`,
  "create.epicMultiplayerMode": `史诗多人模式`,
  "create.singleScenarioMode": `单一场景`,
  "create.miniCampaignMode": `迷你战役`,
  "create.miniCampaignDescription": `<p>按你选择的顺序连续进行三场游戏——每组一场。与常规战役不同：</p><ul><li>使用独立牌组构筑规则。你无需从 0 经验开始。</li><li>玩家可在每个场景之间更换调查员和/或牌组。</li><li>场景之间不获得或消耗经验。</li><li>没有战役日志；调查员不会获得创伤，死亡或陷入疯狂的调查员仍可用于其他场景。</li></ul>`,
  "create.numberOfGroups": `小组数量`,
  "create.groupName": `小组名称`,
  "create.groupPlayers": `玩家`,
  "create.imposeTimeLimit": `设置时间限制`,
  "create.timeLimitMinutes": `时间限制（分钟）`,
  "create.advancedRulesConfiguration": `高级规则配置`,
  "create.rulesPresets": `预设`,
  "create.presetCustom": `自定义`,
  "create.preset.chapter1.name": `第一章`,
  "create.preset.chapter1.description": `推荐用于第一章战役。`,
  "create.preset.chapter2.name": `第二章`,
  "create.preset.chapter2.description": `推荐用于第二章战役。`,
  "create.chapter1Heading": `第一章`,
  "create.chapter2Heading": `第二章`,
  "create.sideStoriesHeading": `支线故事`,
  "create.challengeScenariosHeading": `挑战场景`,
  "create.asIfAtBehavior": `“视作在”行为`,
  "create.asIfAtChapter1": `第一章规则`,
  "create.asIfAtChapter1Description": `“视作在”某地点的效果在整个卡牌或能力持续期间生效，包括来自其他卡牌的窗口触发。`,
  "create.asIfAtChapter2": `第二章规则`,
  "create.asIfAtChapter2Description": `“视作在”某地点仅在指定能力或行动的结算期间生效。其他卡牌能力与窗口触发按实际游戏状态结算。`,
  "cards.label.ajax.moveTwice": `移动两次`,
  "cards.label.ajax.moveToField": `移动到任意田野地点`,
  "cards.label.alienWhispers.damageAsset": `对你控制的一件装备造成 1 点伤害`,
  "cards.label.alienWhispers.horrorAsset": `对你控制的一件装备造成 1 点恐怖`,
  "cards.label.doppelganger1.moveToLocationOfDoppelganger": `移动到复制体所在地点`,
  "cards.label.doppelganger1.evadeEnemy": `躲避敌人`,
  "cards.label.enervation.discardHighestCost": `选择你手牌中印制费用最高的卡牌并将其弃置`,
  "cards.label.corrosiveSlime.devourResource": `实验体 8L-08 吞噬你的一份资源`,
  "cards.label.corrosiveSlime.devourRandomCardFromHand": `实验体 8L-08 吞噬你手牌中的一张随机卡牌`,
  "investigators.joeDiamond.hunchDeck": `直觉牌堆`,
  "label.addCardToDeck": `将 {name} 加入牌组`,
  "label.doNotAddCardToDeck": `不将 {name} 加入牌组`,
  "label.thisEnemyAttacksYou": `该敌人攻击你`,
  "label.changeSlot": `将 {name} 槽位改为 @:{slot} 槽位`,
  "label.changeEmptySlot": `将空的 @:{fromSlot} 槽位改为 @:{slot} 槽位`,
  "label.dealHorror": `造成 {count} 点恐怖`,
  "label.dealDirectDamageAndHorror": `造成 {damage} 点直接伤害与 {horror} 点直接恐怖`,
  "label.dontShuffle": `不要`,
  "label.shuffleJewelOfSarnath": `你可以将撒纳斯之宝石洗入遭遇牌库。`,
  "label.shuffleIn": `将撒纳斯之宝石洗入遭遇牌库`,
  "label.gainClues": `获得 1 点线索（来自混沌袋） | 获得 {count} 点线索（来自混沌袋）`,
  "label.putOnTopOfEncounterDeck": `置于遭遇牌库顶`,
  "label.putOnBottomOfEncounterDeck": `置于遭遇牌库底`,
  "label.nearestInsectEnemyAttacks": `最近的昆虫类敌人准备、移动到你的地点、与你交战，并立即发起一次攻击`,
  "label.cost.addCurseTokens": `向混沌袋中加入 {count} {'{'}curse{'}'}`,
  "label.cost.addCurseTokensEqualToShroud": `向混沌袋中加入等于该地点隐匿值的 {'{'}curse{'}'}`,
  "label.cost.addCurseTokensEqualToTestDifficulty": `向混沌袋中加入等于本次检定难度的 {'{'}curse{'}'}`,
  "label.cost.addFrostTokens": `向混沌袋中加入 {count} {'{'}frost{'}'}`,
  "label.cost.atLeastOne": `至少一项：{inner}`,
  "label.cost.calculated": `计算费用`,
  "label.cost.calculatedHandDiscard": `从手牌中弃置卡牌`,
  "label.cost.calculatedResource": `支付资源`,
  "label.cost.chooseCard": `选择一张卡牌`,
  "label.cost.chooseEnemy": `选择一个敌人`,
  "label.cost.clue": `支付 1 点线索 | 支付 {count} 点线索`,
  "label.cost.costToEnterUnrevealed": `{inner}（用于进入未揭示地点）`,
  "label.cost.directDamageAndHorror": `受到 {damage} 点直接伤害与 {horror} 点直接恐怖`,
  "label.cost.discard": `弃置目标`,
  "label.cost.discardCombined": `弃置合计费用为 {count} 的卡牌`,
  "label.cost.discardFrom": `弃置 {count} 张卡牌`,
  "label.cost.discardHandCount": `从手牌中弃置 {count} 张卡牌`,
  "label.cost.discardHandAny": `从手牌中弃置任意数量的卡牌`,
  "label.cost.discardTopOfDeck": `弃置牌库顶的 {count} 张卡牌`,
  "label.cost.discardUnderneath": `从下方弃置一张卡牌`,
  "label.cost.discoveredClues": `支付已发现的线索`,
  "label.cost.drawEncounterCards": `抽取 {count} 张遭遇卡牌`,
  "label.cost.dynamicUses": `支付 {useType}`,
  "label.cost.enemyAttack": `承受一次机会攻击`,
  "label.cost.enemyDoom": `在一个敌人上放置 {count} 点厄运`,
  "label.cost.eventUses": `支付 {count} {useType}`,
  "label.cost.exhaustXAsset": `无效化 X 件装备`,
  "label.cost.fieldResource": `支付资源`,
  "label.cost.flipScarletKey": `翻转一枚猩红密钥`,
  "label.cost.groupClue": `作为小组支付 {count} 点线索`,
  "label.cost.groupClueX": `作为小组支付 X 点线索`,
  "label.cost.groupClueRange": `作为小组支付 {min}-{max} 点线索`,
  "label.cost.groupDiscard": `小组弃置 {count} 张卡牌`,
  "label.cost.groupResource": `作为小组支付 {count} 份资源`,
  "label.cost.groupSpendKey": `作为小组支付密钥`,
  "label.cost.increaseCostOfThis": `费用增加 {count}`,
  "label.cost.placeClueOnLocation": `在该地点放置 {count} 点线索 | 在该地点放置 {count} 点线索`,
  "label.cost.placeClueOnLocationPerPlayer": `在该地点放置 {count} {'{'}perPlayer{'}'} 点线索 | 在该地点放置 {count} {'{'}perPlayer{'}'} 点线索`,
  "label.cost.placeKey": `放置一枚密钥`,
  "label.cost.removeEnemyDamage": `移除一个敌人受到的伤害`,
  "label.cost.resolveHaunted": `结算每个闹鬼能力`,
  "label.cost.returnChaosTokenToPool": `将混沌令牌归还令牌池`,
  "label.cost.returnChaosTokensToPool": `将 {count} 枚混沌令牌归还令牌池`,
  "label.cost.releaseChaosToken": `释放混沌令牌`,
  "label.cost.releaseChaosTokens": `释放 {count} 枚混沌令牌`,
  "label.cost.sameLocationGroupClue": `从你所在地点支付 {count} 点线索`,
  "label.cost.sameSkillIcon": `提交 {count} 张具有相同技能图标的卡牌`,
  "label.cost.seal": `封印令牌`,
  "label.cost.sealMulti": `封印 {count} 枚令牌`,
  "label.cost.shuffleAttachedIntoDeck": `将附属卡牌洗入牌库`,
  "label.cost.shuffleBonded": `将 {count} 张绑定卡牌洗入牌库`,
  "label.cost.shuffleDiscard": `将弃牌堆中的 {count} 张卡牌洗入牌库`,
  "label.cost.shuffleIntoDeck": `洗入牌库`,
  "label.cost.shuffleTopOfScenarioDeck": `将场景牌库顶的 {count} 张卡牌洗入你的牌库`,
  "label.cost.skillIcon": `提交具有 {count} 个匹配技能图标的卡牌`,
  "label.cost.spendKey": `支付一枚密钥`,
  "label.cost.spendTokenKey": `支付 {count} 枚令牌（作为密钥）`,
  "label.cost.supply": `支付一份补给`,
  "label.cost.upTo": `最多 {inner}`,
  "label.cost.use": `支付 {count} {useType}`,
  "label.cost.useAll": `支付所有 {useType}`,
  "label.cost.useUpTo": `支付 {min}-{max} {useType}`,
  "label.leaveOnTop": `留在顶上`,
  "label.cards.ajax.moveTwice": `移动两次`,
  "label.cards.ajax.moveToField": `移动到任意田野地点`,
  "label.cards.alienWhispers.damageAsset": `对你控制的一件装备造成 1 点伤害`,
  "label.cards.alienWhispers.horrorAsset": `对你控制的一件装备造成 1 点恐怖`,
  "label.cards.doppelganger1.moveToLocationOfDoppelganger": `移动到复制体所在地点`,
  "label.cards.doppelganger1.evadeEnemy": `躲避敌人`,
  "label.cards.enervation.discardHighestCost": `选择你手牌中印制费用最高的卡牌并将其弃置`,
  "label.cards.corrosiveSlime.devourResource": `实验体 8L-08 吞噬你的一份资源`,
  "label.cards.corrosiveSlime.devourRandomCardFromHand": `实验体 8L-08 吞噬你手牌中的一张随机卡牌`
};
