#!/usr/bin/env bash
#
# Emits SQL that stamps `arkham_schema_migrations` with the migrations a fresh
# DB already contains, so a freshly-initialised DB carries an authoritative
# schema baseline. upgrade.sh then applies only genuinely-newer migrations
# instead of guessing whether the DB is current.
#
# setup.sql is a manual pg_dump and can lag the migration plan. Pass the last
# migration your current setup.sql actually contains as the argument; the
# emitted INSERTs cover the plan up to and including it. With no argument, the
# whole plan is stamped (use only when setup.sql is fully current).
#
# Usage (run after regenerating setup.sql):
#   scripts/gen-schema-baseline.sh add_step_constraint >> setup.sql
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLAN="$ROOT/migrations/sqitch.plan"
THROUGH="${1:-}"

names=$(grep -vE '^\s*(%|#|$)' "$PLAN" | awk '{print $1}')
[ -n "$names" ] || { echo "No migrations found in $PLAN" >&2; exit 1; }

if [ -n "$THROUGH" ]; then
  grep -qx "$THROUGH" <<< "$names" || { echo "Migration '$THROUGH' not in plan" >&2; exit 1; }
fi

cat <<'SQL'

--
-- Schema baseline for upgrade.sh (generated by scripts/gen-schema-baseline.sh)
-- Records which migrations this dump already contains so upgrade.sh applies
-- only newer ones. Regenerate this block whenever setup.sql is regenerated.
--
CREATE TABLE IF NOT EXISTS public.arkham_schema_migrations (
    name text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);
SQL

while IFS= read -r n; do
  [ -n "$n" ] || continue
  printf "INSERT INTO public.arkham_schema_migrations (name) VALUES ('%s') ON CONFLICT DO NOTHING;\n" "$n"
  [ "$n" = "$THROUGH" ] && break
done <<< "$names"
