name: arkham-core

language: GHC2021

dependencies:
- base >= 4.7 && < 5

default-extensions:
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- FunctionalDependencies
- GADTs
- LambdaCase
- NoImplicitPrelude
- OverloadedLabels
- OverloadedStrings
- PatternSynonyms
- RecordWildCards
- TypeFamilies
- UndecidableInstances
- ViewPatterns

library:
  source-dirs: library
  dependencies:
    - aeson >= 1.5.4.1
    - lens
    - unordered-containers >= 0.2.12.0
    - monoidal-containers
    - safe
    - these
    - classy-prelude
    - uuid
    - random-shuffle
    - containers
    - text
    - MonadRandom
    - extra
    - aeson-casing
    - aeson-diff
    - mtl
    - these-lens
    - semialign
    - pretty-simple
    - template-haskell
    - newtype
    - constraints

tests:
  spec:
    main: Spec.hs
    source-dirs: tests
    ghc-options: -threaded -rtsopts -O0 "-with-rtsopts=-N"
    dependencies:
      - arkham-core
      - hspec
      - hspec-expectations-lifted
      - lens
      - these
      - uuid
      - unordered-containers >= 0.2.12.0
      - mtl
      - random
      - containers
