name: arkham-core

dependencies:
- base >= 4.7 && < 5

default-extensions:
- NoImplicitPrelude
- RecordWildCards
- DerivingStrategies
- DeriveGeneric
- DeriveAnyClass
- LambdaCase
- FlexibleInstances
- MultiParamTypeClasses
- GeneralizedNewtypeDeriving
- OverloadedStrings
- TypeApplications
- TypeOperators
- TupleSections
- FlexibleContexts
- ConstraintKinds
- StandaloneDeriving
- DerivingVia
- TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - aeson-casing
    - mtl
    - microlens
    - microlens-platform
    - unordered-containers >= 0.2.12.0
    - hashable
    - safe
    - classy-prelude
    - pretty-simple
    - uuid
    - random
    - random-shuffle
    - containers
    - text
    - vector
    - MonadRandom
    - extra
    - generics-sop
    - microlens-th
